package monitor

import (
	"context"

	"github.com/DiegoBulhoes/terraform-provider-uptimekuma/internal/common"
	"github.com/DiegoBulhoes/terraform-provider-uptimekuma/internal/kuma"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// PushModel is a passive monitor: instead of Uptime Kuma probing the
// service, the service calls Uptime Kuma at /api/push/<token>.
type PushModel struct {
	BaseModel

	PushToken types.String `tfsdk:"push_token"`
	PushURL   types.String `tfsdk:"push_url"`
}

var _ Model = (*PushModel)(nil)

func (m *PushModel) Base() *BaseModel { return &m.BaseModel }

func (m *PushModel) ApplyTo(ctx context.Context, wire *kuma.Monitor, diags *diag.Diagnostics) {
	// Sent only when the user pinned a token; otherwise the server generates one.
	wire.PushToken = common.StringPtr(m.PushToken)
	_ = ctx
	_ = diags
}

func (m *PushModel) ReadFrom(ctx context.Context, wire *kuma.Monitor, diags *diag.Diagnostics) {
	m.PushToken = common.StringValue(wire.PushToken)
	// The push URL is not part of the API payload; it is derived from the token,
	// and exposing it saves every caller from rebuilding it by hand.
	if wire.PushToken != nil && *wire.PushToken != "" {
		m.PushURL = types.StringValue("/api/push/" + *wire.PushToken)
	} else {
		m.PushURL = types.StringNull()
	}
	_ = ctx
	_ = diags
}

// NewPushResource returns the uptimekuma_monitor_push resource.
func NewPushResource() resource.Resource {
	return New(TypeDef{
		TypeName: "monitor_push",
		WireType: "push",
		Description: "A passive monitor. Uptime Kuma waits to be called at `/api/push/<push_token>` " +
			"and marks the monitor down when no heartbeat arrives within the interval.",
		Attributes: map[string]schema.Attribute{
			"push_token": schema.StringAttribute{
				Description: "Token embedded in the push URL. Generated by Uptime Kuma when not set.",
				Optional:    true,
				Computed:    true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"push_url": schema.StringAttribute{
				Description: "Path the monitored service should call, relative to the Uptime Kuma base URL.",
				Computed:    true,
			},
		},
		NewModel: func() Model { return &PushModel{} },
	})()
}
