// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/DiegoBulhoes/terraform-provider-uptimekuma/internal/common (interfaces: KumaClient)
//
// Generated by this command:
//
//	mockgen -destination=test/mocks/mock_client.go -package=mocks github.com/DiegoBulhoes/terraform-provider-uptimekuma/internal/common KumaClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kuma "github.com/DiegoBulhoes/terraform-provider-uptimekuma/internal/kuma"
	gomock "go.uber.org/mock/gomock"
)

// MockKumaClient is a mock of KumaClient interface.
type MockKumaClient struct {
	ctrl     *gomock.Controller
	recorder *MockKumaClientMockRecorder
	isgomock struct{}
}

// MockKumaClientMockRecorder is the mock recorder for MockKumaClient.
type MockKumaClientMockRecorder struct {
	mock *MockKumaClient
}

// NewMockKumaClient creates a new mock instance.
func NewMockKumaClient(ctrl *gomock.Controller) *MockKumaClient {
	mock := &MockKumaClient{ctrl: ctrl}
	mock.recorder = &MockKumaClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKumaClient) EXPECT() *MockKumaClientMockRecorder {
	return m.recorder
}

// AddMonitorTag mocks base method.
func (m *MockKumaClient) AddMonitorTag(ctx context.Context, tagID, monitorID int, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMonitorTag", ctx, tagID, monitorID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMonitorTag indicates an expected call of AddMonitorTag.
func (mr *MockKumaClientMockRecorder) AddMonitorTag(ctx, tagID, monitorID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMonitorTag", reflect.TypeOf((*MockKumaClient)(nil).AddMonitorTag), ctx, tagID, monitorID, value)
}

// CreateAPIKey mocks base method.
func (m *MockKumaClient) CreateAPIKey(ctx context.Context, key kuma.APIKey) (int, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAPIKey", ctx, key)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateAPIKey indicates an expected call of CreateAPIKey.
func (mr *MockKumaClientMockRecorder) CreateAPIKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAPIKey", reflect.TypeOf((*MockKumaClient)(nil).CreateAPIKey), ctx, key)
}

// CreateMaintenance mocks base method.
func (m *MockKumaClient) CreateMaintenance(ctx context.Context, maintenance kuma.Maintenance) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMaintenance", ctx, maintenance)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMaintenance indicates an expected call of CreateMaintenance.
func (mr *MockKumaClientMockRecorder) CreateMaintenance(ctx, maintenance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMaintenance", reflect.TypeOf((*MockKumaClient)(nil).CreateMaintenance), ctx, maintenance)
}

// CreateMonitor mocks base method.
func (m *MockKumaClient) CreateMonitor(ctx context.Context, monitor kuma.Monitor) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMonitor", ctx, monitor)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMonitor indicates an expected call of CreateMonitor.
func (mr *MockKumaClientMockRecorder) CreateMonitor(ctx, monitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMonitor", reflect.TypeOf((*MockKumaClient)(nil).CreateMonitor), ctx, monitor)
}

// CreateStatusPage mocks base method.
func (m *MockKumaClient) CreateStatusPage(ctx context.Context, title, slug string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStatusPage", ctx, title, slug)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStatusPage indicates an expected call of CreateStatusPage.
func (mr *MockKumaClientMockRecorder) CreateStatusPage(ctx, title, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStatusPage", reflect.TypeOf((*MockKumaClient)(nil).CreateStatusPage), ctx, title, slug)
}

// CreateTag mocks base method.
func (m *MockKumaClient) CreateTag(ctx context.Context, tag kuma.Tag) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTag", ctx, tag)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTag indicates an expected call of CreateTag.
func (mr *MockKumaClientMockRecorder) CreateTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTag", reflect.TypeOf((*MockKumaClient)(nil).CreateTag), ctx, tag)
}

// DeleteAPIKey mocks base method.
func (m *MockKumaClient) DeleteAPIKey(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAPIKey", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAPIKey indicates an expected call of DeleteAPIKey.
func (mr *MockKumaClientMockRecorder) DeleteAPIKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAPIKey", reflect.TypeOf((*MockKumaClient)(nil).DeleteAPIKey), ctx, id)
}

// DeleteDockerHost mocks base method.
func (m *MockKumaClient) DeleteDockerHost(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteDockerHost", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDockerHost indicates an expected call of DeleteDockerHost.
func (mr *MockKumaClientMockRecorder) DeleteDockerHost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDockerHost", reflect.TypeOf((*MockKumaClient)(nil).DeleteDockerHost), ctx, id)
}

// DeleteIncident mocks base method.
func (m *MockKumaClient) DeleteIncident(ctx context.Context, slug string, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteIncident", ctx, slug, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteIncident indicates an expected call of DeleteIncident.
func (mr *MockKumaClientMockRecorder) DeleteIncident(ctx, slug, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteIncident", reflect.TypeOf((*MockKumaClient)(nil).DeleteIncident), ctx, slug, id)
}

// DeleteMaintenance mocks base method.
func (m *MockKumaClient) DeleteMaintenance(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMaintenance", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMaintenance indicates an expected call of DeleteMaintenance.
func (mr *MockKumaClientMockRecorder) DeleteMaintenance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMaintenance", reflect.TypeOf((*MockKumaClient)(nil).DeleteMaintenance), ctx, id)
}

// DeleteMonitor mocks base method.
func (m *MockKumaClient) DeleteMonitor(ctx context.Context, id int, deleteChildren bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMonitor", ctx, id, deleteChildren)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMonitor indicates an expected call of DeleteMonitor.
func (mr *MockKumaClientMockRecorder) DeleteMonitor(ctx, id, deleteChildren any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMonitor", reflect.TypeOf((*MockKumaClient)(nil).DeleteMonitor), ctx, id, deleteChildren)
}

// DeleteMonitorTag mocks base method.
func (m *MockKumaClient) DeleteMonitorTag(ctx context.Context, tagID, monitorID int, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMonitorTag", ctx, tagID, monitorID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMonitorTag indicates an expected call of DeleteMonitorTag.
func (mr *MockKumaClientMockRecorder) DeleteMonitorTag(ctx, tagID, monitorID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMonitorTag", reflect.TypeOf((*MockKumaClient)(nil).DeleteMonitorTag), ctx, tagID, monitorID, value)
}

// DeleteNotification mocks base method.
func (m *MockKumaClient) DeleteNotification(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteNotification", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteNotification indicates an expected call of DeleteNotification.
func (mr *MockKumaClientMockRecorder) DeleteNotification(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteNotification", reflect.TypeOf((*MockKumaClient)(nil).DeleteNotification), ctx, id)
}

// DeleteProxy mocks base method.
func (m *MockKumaClient) DeleteProxy(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProxy", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProxy indicates an expected call of DeleteProxy.
func (mr *MockKumaClientMockRecorder) DeleteProxy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProxy", reflect.TypeOf((*MockKumaClient)(nil).DeleteProxy), ctx, id)
}

// DeleteRemoteBrowser mocks base method.
func (m *MockKumaClient) DeleteRemoteBrowser(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRemoteBrowser", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRemoteBrowser indicates an expected call of DeleteRemoteBrowser.
func (mr *MockKumaClientMockRecorder) DeleteRemoteBrowser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRemoteBrowser", reflect.TypeOf((*MockKumaClient)(nil).DeleteRemoteBrowser), ctx, id)
}

// DeleteStatusPage mocks base method.
func (m *MockKumaClient) DeleteStatusPage(ctx context.Context, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteStatusPage", ctx, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteStatusPage indicates an expected call of DeleteStatusPage.
func (mr *MockKumaClientMockRecorder) DeleteStatusPage(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteStatusPage", reflect.TypeOf((*MockKumaClient)(nil).DeleteStatusPage), ctx, slug)
}

// DeleteTag mocks base method.
func (m *MockKumaClient) DeleteTag(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTag", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTag indicates an expected call of DeleteTag.
func (mr *MockKumaClientMockRecorder) DeleteTag(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTag", reflect.TypeOf((*MockKumaClient)(nil).DeleteTag), ctx, id)
}

// EditIncident mocks base method.
func (m *MockKumaClient) EditIncident(ctx context.Context, slug string, id int, incident kuma.StatusPageIncident) (*kuma.StatusPageIncident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditIncident", ctx, slug, id, incident)
	ret0, _ := ret[0].(*kuma.StatusPageIncident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditIncident indicates an expected call of EditIncident.
func (mr *MockKumaClientMockRecorder) EditIncident(ctx, slug, id, incident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditIncident", reflect.TypeOf((*MockKumaClient)(nil).EditIncident), ctx, slug, id, incident)
}

// EditMonitorTag mocks base method.
func (m *MockKumaClient) EditMonitorTag(ctx context.Context, tagID, monitorID int, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditMonitorTag", ctx, tagID, monitorID, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// EditMonitorTag indicates an expected call of EditMonitorTag.
func (mr *MockKumaClientMockRecorder) EditMonitorTag(ctx, tagID, monitorID, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditMonitorTag", reflect.TypeOf((*MockKumaClient)(nil).EditMonitorTag), ctx, tagID, monitorID, value)
}

// GetAPIKey mocks base method.
func (m *MockKumaClient) GetAPIKey(ctx context.Context, id int) (*kuma.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIKey", ctx, id)
	ret0, _ := ret[0].(*kuma.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAPIKey indicates an expected call of GetAPIKey.
func (mr *MockKumaClientMockRecorder) GetAPIKey(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIKey", reflect.TypeOf((*MockKumaClient)(nil).GetAPIKey), ctx, id)
}

// GetDockerHost mocks base method.
func (m *MockKumaClient) GetDockerHost(ctx context.Context, id int) (*kuma.DockerHost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDockerHost", ctx, id)
	ret0, _ := ret[0].(*kuma.DockerHost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDockerHost indicates an expected call of GetDockerHost.
func (mr *MockKumaClientMockRecorder) GetDockerHost(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDockerHost", reflect.TypeOf((*MockKumaClient)(nil).GetDockerHost), ctx, id)
}

// GetIncidentHistory mocks base method.
func (m *MockKumaClient) GetIncidentHistory(ctx context.Context, slug string) ([]kuma.StatusPageIncident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIncidentHistory", ctx, slug)
	ret0, _ := ret[0].([]kuma.StatusPageIncident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIncidentHistory indicates an expected call of GetIncidentHistory.
func (mr *MockKumaClientMockRecorder) GetIncidentHistory(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIncidentHistory", reflect.TypeOf((*MockKumaClient)(nil).GetIncidentHistory), ctx, slug)
}

// GetMaintenance mocks base method.
func (m *MockKumaClient) GetMaintenance(ctx context.Context, id int) (*kuma.Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaintenance", ctx, id)
	ret0, _ := ret[0].(*kuma.Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaintenance indicates an expected call of GetMaintenance.
func (mr *MockKumaClientMockRecorder) GetMaintenance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaintenance", reflect.TypeOf((*MockKumaClient)(nil).GetMaintenance), ctx, id)
}

// GetMaintenanceMonitors mocks base method.
func (m *MockKumaClient) GetMaintenanceMonitors(ctx context.Context, maintenanceID int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaintenanceMonitors", ctx, maintenanceID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaintenanceMonitors indicates an expected call of GetMaintenanceMonitors.
func (mr *MockKumaClientMockRecorder) GetMaintenanceMonitors(ctx, maintenanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaintenanceMonitors", reflect.TypeOf((*MockKumaClient)(nil).GetMaintenanceMonitors), ctx, maintenanceID)
}

// GetMaintenanceStatusPages mocks base method.
func (m *MockKumaClient) GetMaintenanceStatusPages(ctx context.Context, maintenanceID int) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMaintenanceStatusPages", ctx, maintenanceID)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMaintenanceStatusPages indicates an expected call of GetMaintenanceStatusPages.
func (mr *MockKumaClientMockRecorder) GetMaintenanceStatusPages(ctx, maintenanceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMaintenanceStatusPages", reflect.TypeOf((*MockKumaClient)(nil).GetMaintenanceStatusPages), ctx, maintenanceID)
}

// GetMonitor mocks base method.
func (m *MockKumaClient) GetMonitor(ctx context.Context, id int) (*kuma.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMonitor", ctx, id)
	ret0, _ := ret[0].(*kuma.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMonitor indicates an expected call of GetMonitor.
func (mr *MockKumaClientMockRecorder) GetMonitor(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMonitor", reflect.TypeOf((*MockKumaClient)(nil).GetMonitor), ctx, id)
}

// GetNotification mocks base method.
func (m *MockKumaClient) GetNotification(ctx context.Context, id int) (*kuma.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNotification", ctx, id)
	ret0, _ := ret[0].(*kuma.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNotification indicates an expected call of GetNotification.
func (mr *MockKumaClientMockRecorder) GetNotification(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNotification", reflect.TypeOf((*MockKumaClient)(nil).GetNotification), ctx, id)
}

// GetProxy mocks base method.
func (m *MockKumaClient) GetProxy(ctx context.Context, id int) (*kuma.Proxy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProxy", ctx, id)
	ret0, _ := ret[0].(*kuma.Proxy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProxy indicates an expected call of GetProxy.
func (mr *MockKumaClientMockRecorder) GetProxy(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProxy", reflect.TypeOf((*MockKumaClient)(nil).GetProxy), ctx, id)
}

// GetRemoteBrowser mocks base method.
func (m *MockKumaClient) GetRemoteBrowser(ctx context.Context, id int) (*kuma.RemoteBrowser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRemoteBrowser", ctx, id)
	ret0, _ := ret[0].(*kuma.RemoteBrowser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRemoteBrowser indicates an expected call of GetRemoteBrowser.
func (mr *MockKumaClientMockRecorder) GetRemoteBrowser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRemoteBrowser", reflect.TypeOf((*MockKumaClient)(nil).GetRemoteBrowser), ctx, id)
}

// GetSettings mocks base method.
func (m *MockKumaClient) GetSettings(ctx context.Context) (map[string]any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings", ctx)
	ret0, _ := ret[0].(map[string]any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockKumaClientMockRecorder) GetSettings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockKumaClient)(nil).GetSettings), ctx)
}

// GetStatusPage mocks base method.
func (m *MockKumaClient) GetStatusPage(ctx context.Context, slug string) (*kuma.StatusPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusPage", ctx, slug)
	ret0, _ := ret[0].(*kuma.StatusPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusPage indicates an expected call of GetStatusPage.
func (mr *MockKumaClientMockRecorder) GetStatusPage(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusPage", reflect.TypeOf((*MockKumaClient)(nil).GetStatusPage), ctx, slug)
}

// GetStatusPageGroups mocks base method.
func (m *MockKumaClient) GetStatusPageGroups(ctx context.Context, slug string) ([]kuma.StatusPageGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatusPageGroups", ctx, slug)
	ret0, _ := ret[0].([]kuma.StatusPageGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStatusPageGroups indicates an expected call of GetStatusPageGroups.
func (mr *MockKumaClientMockRecorder) GetStatusPageGroups(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatusPageGroups", reflect.TypeOf((*MockKumaClient)(nil).GetStatusPageGroups), ctx, slug)
}

// GetTag mocks base method.
func (m *MockKumaClient) GetTag(ctx context.Context, id int) (*kuma.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTag", ctx, id)
	ret0, _ := ret[0].(*kuma.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTag indicates an expected call of GetTag.
func (mr *MockKumaClientMockRecorder) GetTag(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTag", reflect.TypeOf((*MockKumaClient)(nil).GetTag), ctx, id)
}

// Info mocks base method.
func (m *MockKumaClient) Info() kuma.ServerInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Info")
	ret0, _ := ret[0].(kuma.ServerInfo)
	return ret0
}

// Info indicates an expected call of Info.
func (mr *MockKumaClientMockRecorder) Info() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockKumaClient)(nil).Info))
}

// ListAPIKeys mocks base method.
func (m *MockKumaClient) ListAPIKeys(ctx context.Context) (map[int]kuma.APIKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAPIKeys", ctx)
	ret0, _ := ret[0].(map[int]kuma.APIKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAPIKeys indicates an expected call of ListAPIKeys.
func (mr *MockKumaClientMockRecorder) ListAPIKeys(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAPIKeys", reflect.TypeOf((*MockKumaClient)(nil).ListAPIKeys), ctx)
}

// ListDockerHosts mocks base method.
func (m *MockKumaClient) ListDockerHosts(ctx context.Context) (map[int]kuma.DockerHost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDockerHosts", ctx)
	ret0, _ := ret[0].(map[int]kuma.DockerHost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDockerHosts indicates an expected call of ListDockerHosts.
func (mr *MockKumaClientMockRecorder) ListDockerHosts(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDockerHosts", reflect.TypeOf((*MockKumaClient)(nil).ListDockerHosts), ctx)
}

// ListMaintenances mocks base method.
func (m *MockKumaClient) ListMaintenances(ctx context.Context) (map[int]kuma.Maintenance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMaintenances", ctx)
	ret0, _ := ret[0].(map[int]kuma.Maintenance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMaintenances indicates an expected call of ListMaintenances.
func (mr *MockKumaClientMockRecorder) ListMaintenances(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMaintenances", reflect.TypeOf((*MockKumaClient)(nil).ListMaintenances), ctx)
}

// ListMonitors mocks base method.
func (m *MockKumaClient) ListMonitors(ctx context.Context) (map[int]kuma.Monitor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMonitors", ctx)
	ret0, _ := ret[0].(map[int]kuma.Monitor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMonitors indicates an expected call of ListMonitors.
func (mr *MockKumaClientMockRecorder) ListMonitors(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMonitors", reflect.TypeOf((*MockKumaClient)(nil).ListMonitors), ctx)
}

// ListNotifications mocks base method.
func (m *MockKumaClient) ListNotifications(ctx context.Context) (map[int]kuma.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListNotifications", ctx)
	ret0, _ := ret[0].(map[int]kuma.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNotifications indicates an expected call of ListNotifications.
func (mr *MockKumaClientMockRecorder) ListNotifications(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNotifications", reflect.TypeOf((*MockKumaClient)(nil).ListNotifications), ctx)
}

// ListProxies mocks base method.
func (m *MockKumaClient) ListProxies(ctx context.Context) (map[int]kuma.Proxy, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProxies", ctx)
	ret0, _ := ret[0].(map[int]kuma.Proxy)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProxies indicates an expected call of ListProxies.
func (mr *MockKumaClientMockRecorder) ListProxies(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProxies", reflect.TypeOf((*MockKumaClient)(nil).ListProxies), ctx)
}

// ListRemoteBrowsers mocks base method.
func (m *MockKumaClient) ListRemoteBrowsers(ctx context.Context) (map[int]kuma.RemoteBrowser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRemoteBrowsers", ctx)
	ret0, _ := ret[0].(map[int]kuma.RemoteBrowser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRemoteBrowsers indicates an expected call of ListRemoteBrowsers.
func (mr *MockKumaClientMockRecorder) ListRemoteBrowsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRemoteBrowsers", reflect.TypeOf((*MockKumaClient)(nil).ListRemoteBrowsers), ctx)
}

// ListStatusPages mocks base method.
func (m *MockKumaClient) ListStatusPages(ctx context.Context, refresh bool) (map[int]kuma.StatusPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStatusPages", ctx, refresh)
	ret0, _ := ret[0].(map[int]kuma.StatusPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStatusPages indicates an expected call of ListStatusPages.
func (mr *MockKumaClientMockRecorder) ListStatusPages(ctx, refresh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStatusPages", reflect.TypeOf((*MockKumaClient)(nil).ListStatusPages), ctx, refresh)
}

// ListTags mocks base method.
func (m *MockKumaClient) ListTags(ctx context.Context) ([]kuma.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTags", ctx)
	ret0, _ := ret[0].([]kuma.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTags indicates an expected call of ListTags.
func (mr *MockKumaClientMockRecorder) ListTags(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTags", reflect.TypeOf((*MockKumaClient)(nil).ListTags), ctx)
}

// PauseMaintenance mocks base method.
func (m *MockKumaClient) PauseMaintenance(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseMaintenance", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseMaintenance indicates an expected call of PauseMaintenance.
func (mr *MockKumaClientMockRecorder) PauseMaintenance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseMaintenance", reflect.TypeOf((*MockKumaClient)(nil).PauseMaintenance), ctx, id)
}

// PauseMonitor mocks base method.
func (m *MockKumaClient) PauseMonitor(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PauseMonitor", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// PauseMonitor indicates an expected call of PauseMonitor.
func (mr *MockKumaClientMockRecorder) PauseMonitor(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PauseMonitor", reflect.TypeOf((*MockKumaClient)(nil).PauseMonitor), ctx, id)
}

// PostIncident mocks base method.
func (m *MockKumaClient) PostIncident(ctx context.Context, slug string, incident kuma.StatusPageIncident) (*kuma.StatusPageIncident, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostIncident", ctx, slug, incident)
	ret0, _ := ret[0].(*kuma.StatusPageIncident)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostIncident indicates an expected call of PostIncident.
func (mr *MockKumaClientMockRecorder) PostIncident(ctx, slug, incident any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostIncident", reflect.TypeOf((*MockKumaClient)(nil).PostIncident), ctx, slug, incident)
}

// ResolveIncident mocks base method.
func (m *MockKumaClient) ResolveIncident(ctx context.Context, slug string, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveIncident", ctx, slug, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResolveIncident indicates an expected call of ResolveIncident.
func (mr *MockKumaClientMockRecorder) ResolveIncident(ctx, slug, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveIncident", reflect.TypeOf((*MockKumaClient)(nil).ResolveIncident), ctx, slug, id)
}

// ResumeMaintenance mocks base method.
func (m *MockKumaClient) ResumeMaintenance(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeMaintenance", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeMaintenance indicates an expected call of ResumeMaintenance.
func (mr *MockKumaClientMockRecorder) ResumeMaintenance(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeMaintenance", reflect.TypeOf((*MockKumaClient)(nil).ResumeMaintenance), ctx, id)
}

// ResumeMonitor mocks base method.
func (m *MockKumaClient) ResumeMonitor(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResumeMonitor", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// ResumeMonitor indicates an expected call of ResumeMonitor.
func (mr *MockKumaClientMockRecorder) ResumeMonitor(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResumeMonitor", reflect.TypeOf((*MockKumaClient)(nil).ResumeMonitor), ctx, id)
}

// SaveDockerHost mocks base method.
func (m *MockKumaClient) SaveDockerHost(ctx context.Context, id *int, host kuma.DockerHost) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveDockerHost", ctx, id, host)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveDockerHost indicates an expected call of SaveDockerHost.
func (mr *MockKumaClientMockRecorder) SaveDockerHost(ctx, id, host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveDockerHost", reflect.TypeOf((*MockKumaClient)(nil).SaveDockerHost), ctx, id, host)
}

// SaveNotification mocks base method.
func (m *MockKumaClient) SaveNotification(ctx context.Context, id *int, payload map[string]any) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveNotification", ctx, id, payload)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveNotification indicates an expected call of SaveNotification.
func (mr *MockKumaClientMockRecorder) SaveNotification(ctx, id, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveNotification", reflect.TypeOf((*MockKumaClient)(nil).SaveNotification), ctx, id, payload)
}

// SaveProxy mocks base method.
func (m *MockKumaClient) SaveProxy(ctx context.Context, id *int, proxy kuma.Proxy) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProxy", ctx, id, proxy)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveProxy indicates an expected call of SaveProxy.
func (mr *MockKumaClientMockRecorder) SaveProxy(ctx, id, proxy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProxy", reflect.TypeOf((*MockKumaClient)(nil).SaveProxy), ctx, id, proxy)
}

// SaveRemoteBrowser mocks base method.
func (m *MockKumaClient) SaveRemoteBrowser(ctx context.Context, id *int, browser kuma.RemoteBrowser) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveRemoteBrowser", ctx, id, browser)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveRemoteBrowser indicates an expected call of SaveRemoteBrowser.
func (mr *MockKumaClientMockRecorder) SaveRemoteBrowser(ctx, id, browser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveRemoteBrowser", reflect.TypeOf((*MockKumaClient)(nil).SaveRemoteBrowser), ctx, id, browser)
}

// SaveStatusPage mocks base method.
func (m *MockKumaClient) SaveStatusPage(ctx context.Context, slug string, config kuma.StatusPage, icon string, groups []kuma.StatusPageGroup) ([]kuma.StatusPageGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveStatusPage", ctx, slug, config, icon, groups)
	ret0, _ := ret[0].([]kuma.StatusPageGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveStatusPage indicates an expected call of SaveStatusPage.
func (mr *MockKumaClientMockRecorder) SaveStatusPage(ctx, slug, config, icon, groups any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveStatusPage", reflect.TypeOf((*MockKumaClient)(nil).SaveStatusPage), ctx, slug, config, icon, groups)
}

// SetAPIKeyActive mocks base method.
func (m *MockKumaClient) SetAPIKeyActive(ctx context.Context, id int, active bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAPIKeyActive", ctx, id, active)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAPIKeyActive indicates an expected call of SetAPIKeyActive.
func (mr *MockKumaClientMockRecorder) SetAPIKeyActive(ctx, id, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAPIKeyActive", reflect.TypeOf((*MockKumaClient)(nil).SetAPIKeyActive), ctx, id, active)
}

// SetMaintenanceMonitors mocks base method.
func (m *MockKumaClient) SetMaintenanceMonitors(ctx context.Context, maintenanceID int, monitorIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaintenanceMonitors", ctx, maintenanceID, monitorIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaintenanceMonitors indicates an expected call of SetMaintenanceMonitors.
func (mr *MockKumaClientMockRecorder) SetMaintenanceMonitors(ctx, maintenanceID, monitorIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaintenanceMonitors", reflect.TypeOf((*MockKumaClient)(nil).SetMaintenanceMonitors), ctx, maintenanceID, monitorIDs)
}

// SetMaintenanceStatusPages mocks base method.
func (m *MockKumaClient) SetMaintenanceStatusPages(ctx context.Context, maintenanceID int, statusPageIDs []int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMaintenanceStatusPages", ctx, maintenanceID, statusPageIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMaintenanceStatusPages indicates an expected call of SetMaintenanceStatusPages.
func (mr *MockKumaClientMockRecorder) SetMaintenanceStatusPages(ctx, maintenanceID, statusPageIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMaintenanceStatusPages", reflect.TypeOf((*MockKumaClient)(nil).SetMaintenanceStatusPages), ctx, maintenanceID, statusPageIDs)
}

// SetSettings mocks base method.
func (m *MockKumaClient) SetSettings(ctx context.Context, settings map[string]any, currentPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSettings", ctx, settings, currentPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSettings indicates an expected call of SetSettings.
func (mr *MockKumaClientMockRecorder) SetSettings(ctx, settings, currentPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSettings", reflect.TypeOf((*MockKumaClient)(nil).SetSettings), ctx, settings, currentPassword)
}

// UnpinIncident mocks base method.
func (m *MockKumaClient) UnpinIncident(ctx context.Context, slug string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnpinIncident", ctx, slug)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnpinIncident indicates an expected call of UnpinIncident.
func (mr *MockKumaClientMockRecorder) UnpinIncident(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnpinIncident", reflect.TypeOf((*MockKumaClient)(nil).UnpinIncident), ctx, slug)
}

// UpdateMaintenance mocks base method.
func (m *MockKumaClient) UpdateMaintenance(ctx context.Context, maintenance kuma.Maintenance) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMaintenance", ctx, maintenance)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMaintenance indicates an expected call of UpdateMaintenance.
func (mr *MockKumaClientMockRecorder) UpdateMaintenance(ctx, maintenance any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMaintenance", reflect.TypeOf((*MockKumaClient)(nil).UpdateMaintenance), ctx, maintenance)
}

// UpdateMonitor mocks base method.
func (m *MockKumaClient) UpdateMonitor(ctx context.Context, monitor kuma.Monitor) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMonitor", ctx, monitor)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMonitor indicates an expected call of UpdateMonitor.
func (mr *MockKumaClientMockRecorder) UpdateMonitor(ctx, monitor any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMonitor", reflect.TypeOf((*MockKumaClient)(nil).UpdateMonitor), ctx, monitor)
}

// UpdateTag mocks base method.
func (m *MockKumaClient) UpdateTag(ctx context.Context, tag kuma.Tag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", ctx, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockKumaClientMockRecorder) UpdateTag(ctx, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockKumaClient)(nil).UpdateTag), ctx, tag)
}
